#define ARGUMENT_H "../headers/argument.h"
#define CHOICE_H "../headers/choice.h"
#define CLOSE_H "../headers/close.h"
#define ERROR_H "../headers/error.h"
#define OUTPUT_H "../headers/output.h"
#define TERMINAL_H "../headers/terminal.h"
